definitions:
  services:
    build-app: &build-app
      name: Build project (dev)
      image: maven:3.8.4-jdk-11
      artifacts:
        - target/*.jar
      script:
        #Build project
        - mvn package
    push-image-dev: &push-image-dev
      name: Build and Push Docker Image (DEV)
      image: atlassian/pipelines-awscli
      caches:
        - docker
      services:
        - docker
      script:
        - docker build -t ${IMAGE_NAME} .
        - docker tag ${IMAGE_TAG}
        - pipe: atlassian/aws-ecr-push-image:1.5.0
          variables:
            AWS_OIDC_ROLE_ARN: ${AWS_ROLE_ARN}
            IMAGE_NAME: ${IMAGE_NAME}
            TAGS: "dev latest"
            AWS_DEFAULT_REGION: "${AWS_REGION}"
      oidc: true

    deploy-to-ecs-dev: &deploy-to-ecs-dev
      name: Deploy to ECS (DEV)
      image: atlassian/pipelines-awscli
      script:
        - pipe: atlassian/aws-ecs-deploy:1.6.2
          variables:
            AWS_DEFAULT_REGION: ${AWS_REGION}
            CLUSTER_NAME: ${CLUSTER_NAME_DEV}
            SERVICE_NAME: ${SERVICE_NAME_DEV}
            FORCE_NEW_DEPLOYMENT: "true"
            AWS_OIDC_ROLE_ARN: ${AWS_ROLE_ARN}
      oidc: true

    push-image-prod: &push-image-prod
      trigger: manual
      name: Build and Push Docker Image (PROD)
      image: atlassian/pipelines-awscli
      caches:
        - docker
      services:
        - docker
      script:
        - docker build -t ${IMAGE_NAME} .
        - docker tag ${IMAGE_TAG}
        - pipe: atlassian/aws-ecr-push-image:1.5.0
          variables:
            AWS_OIDC_ROLE_ARN: ${AWS_ROLE_ARN}
            IMAGE_NAME: ${IMAGE_NAME}
            TAGS: "prod latest"
            AWS_DEFAULT_REGION: "${AWS_REGION}"
      oidc: true

    deploy-to-ecs-prod: &deploy-to-ecs-prod
      trigger: manual
      name: Deploy to ECS (PROD)
      image: atlassian/pipelines-awscli
      script:
        - pipe: atlassian/aws-ecs-deploy:1.6.2
          variables:
            AWS_DEFAULT_REGION: ${AWS_REGION}
            CLUSTER_NAME: ${CLUSTER_NAME_PROD}
            SERVICE_NAME: ${SERVICE_NAME_PROD}
            FORCE_NEW_DEPLOYMENT: "true"
            AWS_OIDC_ROLE_ARN: ${AWS_ROLE_ARN}
      oidc: true

pipelines:
  branches:
    develop:
      - step: *build-app
      - step: *push-image-dev
      - step: *deploy-to-ecs-dev
    Live-Interactive:
      - step: *build-app
      - step: *push-image-dev
      - step: *deploy-to-ecs-dev
    master:
      - step: *build-app
      - step: *push-image-dev
      - step: *deploy-to-ecs-dev
      - step: *push-image-prod
      - step: *deploy-to-ecs-prod